// SPDX-FileCopyrightText: 2026 Matthew Milner <matterhorn103@proton.me>
//
// SPDX-License-Identifier: MPL-2.0
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

use mendeleev;
use mendeleev::OxidationStateCategory;

#[derive(Copy, Clone, Debug, Hash, Eq, PartialEq, Ord, PartialOrd)]
//#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum Element {
    H,
    He,
    Li,
    Be,
    B,
    C,
    N,
    O,
    F,
    Ne,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    Ar,
    K,
    Ca,
    Sc,
    Ti,
    V,
    Cr,
    Mn,
    Fe,
    Co,
    Ni,
    Cu,
    Zn,
    Ga,
    Ge,
    As,
    Se,
    Br,
    Kr,
    Rb,
    Sr,
    Y,
    Zr,
    Nb,
    Mo,
    Tc,
    Ru,
    Rh,
    Pd,
    Ag,
    Cd,
    In,
    Sn,
    Sb,
    Te,
    I,
    Xe,
    Cs,
    Ba,
    La,
    Ce,
    Pr,
    Nd,
    Pm,
    Sm,
    Eu,
    Gd,
    Tb,
    Dy,
    Ho,
    Er,
    Tm,
    Yb,
    Lu,
    Hf,
    Ta,
    W,
    Re,
    Os,
    Ir,
    Pt,
    Au,
    Hg,
    Tl,
    Pb,
    Bi,
    Po,
    At,
    Rn,
    Fr,
    Ra,
    Ac,
    Th,
    Pa,
    U,
    Np,
    Pu,
    Am,
    Cm,
    Bk,
    Cf,
    Es,
    Fm,
    Md,
    No,
    Lr,
    Rf,
    Db,
    Sg,
    Bh,
    Hs,
    Mt,
    Ds,
    Rg,
    Cn,
    Nh,
    Fl,
    Mc,
    Lv,
    Ts,
    Og,
}

impl Element {
    const fn into_mendeleev(self) -> mendeleev::Element {
        match self {
            Self::H => mendeleev::Element::H,
            Self::He => mendeleev::Element::He,
            Self::Li => mendeleev::Element::Li,
            Self::Be => mendeleev::Element::Be,
            Self::B => mendeleev::Element::B,
            Self::C => mendeleev::Element::C,
            Self::N => mendeleev::Element::N,
            Self::O => mendeleev::Element::O,
            Self::F => mendeleev::Element::F,
            Self::Ne => mendeleev::Element::Ne,
            Self::Na => mendeleev::Element::Na,
            Self::Mg => mendeleev::Element::Mg,
            Self::Al => mendeleev::Element::Al,
            Self::Si => mendeleev::Element::Si,
            Self::P => mendeleev::Element::P,
            Self::S => mendeleev::Element::S,
            Self::Cl => mendeleev::Element::Cl,
            Self::Ar => mendeleev::Element::Ar,
            Self::K => mendeleev::Element::K,
            Self::Ca => mendeleev::Element::Ca,
            Self::Sc => mendeleev::Element::Sc,
            Self::Ti => mendeleev::Element::Ti,
            Self::V => mendeleev::Element::V,
            Self::Cr => mendeleev::Element::Cr,
            Self::Mn => mendeleev::Element::Mn,
            Self::Fe => mendeleev::Element::Fe,
            Self::Co => mendeleev::Element::Co,
            Self::Ni => mendeleev::Element::Ni,
            Self::Cu => mendeleev::Element::Cu,
            Self::Zn => mendeleev::Element::Zn,
            Self::Ga => mendeleev::Element::Ga,
            Self::Ge => mendeleev::Element::Ge,
            Self::As => mendeleev::Element::As,
            Self::Se => mendeleev::Element::Se,
            Self::Br => mendeleev::Element::Br,
            Self::Kr => mendeleev::Element::Kr,
            Self::Rb => mendeleev::Element::Rb,
            Self::Sr => mendeleev::Element::Sr,
            Self::Y => mendeleev::Element::Y,
            Self::Zr => mendeleev::Element::Zr,
            Self::Nb => mendeleev::Element::Nb,
            Self::Mo => mendeleev::Element::Mo,
            Self::Tc => mendeleev::Element::Tc,
            Self::Ru => mendeleev::Element::Ru,
            Self::Rh => mendeleev::Element::Rh,
            Self::Pd => mendeleev::Element::Pd,
            Self::Ag => mendeleev::Element::Ag,
            Self::Cd => mendeleev::Element::Cd,
            Self::In => mendeleev::Element::In,
            Self::Sn => mendeleev::Element::Sn,
            Self::Sb => mendeleev::Element::Sb,
            Self::Te => mendeleev::Element::Te,
            Self::I => mendeleev::Element::I,
            Self::Xe => mendeleev::Element::Xe,
            Self::Cs => mendeleev::Element::Cs,
            Self::Ba => mendeleev::Element::Ba,
            Self::La => mendeleev::Element::La,
            Self::Ce => mendeleev::Element::Ce,
            Self::Pr => mendeleev::Element::Pr,
            Self::Nd => mendeleev::Element::Nd,
            Self::Pm => mendeleev::Element::Pm,
            Self::Sm => mendeleev::Element::Sm,
            Self::Eu => mendeleev::Element::Eu,
            Self::Gd => mendeleev::Element::Gd,
            Self::Tb => mendeleev::Element::Tb,
            Self::Dy => mendeleev::Element::Dy,
            Self::Ho => mendeleev::Element::Ho,
            Self::Er => mendeleev::Element::Er,
            Self::Tm => mendeleev::Element::Tm,
            Self::Yb => mendeleev::Element::Yb,
            Self::Lu => mendeleev::Element::Lu,
            Self::Hf => mendeleev::Element::Hf,
            Self::Ta => mendeleev::Element::Ta,
            Self::W => mendeleev::Element::W,
            Self::Re => mendeleev::Element::Re,
            Self::Os => mendeleev::Element::Os,
            Self::Ir => mendeleev::Element::Ir,
            Self::Pt => mendeleev::Element::Pt,
            Self::Au => mendeleev::Element::Au,
            Self::Hg => mendeleev::Element::Hg,
            Self::Tl => mendeleev::Element::Tl,
            Self::Pb => mendeleev::Element::Pb,
            Self::Bi => mendeleev::Element::Bi,
            Self::Po => mendeleev::Element::Po,
            Self::At => mendeleev::Element::At,
            Self::Rn => mendeleev::Element::Rn,
            Self::Fr => mendeleev::Element::Fr,
            Self::Ra => mendeleev::Element::Ra,
            Self::Ac => mendeleev::Element::Ac,
            Self::Th => mendeleev::Element::Th,
            Self::Pa => mendeleev::Element::Pa,
            Self::U => mendeleev::Element::U,
            Self::Np => mendeleev::Element::Np,
            Self::Pu => mendeleev::Element::Pu,
            Self::Am => mendeleev::Element::Am,
            Self::Cm => mendeleev::Element::Cm,
            Self::Bk => mendeleev::Element::Bk,
            Self::Cf => mendeleev::Element::Cf,
            Self::Es => mendeleev::Element::Es,
            Self::Fm => mendeleev::Element::Fm,
            Self::Md => mendeleev::Element::Md,
            Self::No => mendeleev::Element::No,
            Self::Lr => mendeleev::Element::Lr,
            Self::Rf => mendeleev::Element::Rf,
            Self::Db => mendeleev::Element::Db,
            Self::Sg => mendeleev::Element::Sg,
            Self::Bh => mendeleev::Element::Bh,
            Self::Hs => mendeleev::Element::Hs,
            Self::Mt => mendeleev::Element::Mt,
            Self::Ds => mendeleev::Element::Ds,
            Self::Rg => mendeleev::Element::Rg,
            Self::Cn => mendeleev::Element::Cn,
            Self::Nh => mendeleev::Element::Nh,
            Self::Fl => mendeleev::Element::Fl,
            Self::Mc => mendeleev::Element::Mc,
            Self::Lv => mendeleev::Element::Lv,
            Self::Ts => mendeleev::Element::Ts,
            Self::Og => mendeleev::Element::Og,
        }
    }

    pub fn default_valency(&self) -> u8 {
        self.into_mendeleev()
            .oxidation_states(OxidationStateCategory::Main)[0]
            .abs()
            .try_into()
            .expect("Oxidation state should be positive after taking absolute value")
    }

    pub fn symbol(&self) -> &str {
        self.into_mendeleev().symbol()
    }
}
